/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_salton123_jpeg_JpegTurbo */

#ifndef _Included_com_salton123_jpeg_JpegTurbo
#define _Included_com_salton123_jpeg_JpegTurbo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_salton123_jpeg_JpegTurbo
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_salton123_jpeg_JpegTurbo_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
